_wandb:
    value:
        cli_version: 0.22.3
        e:
            9zod7pa6stccdx7oy2xhokz40f3afuzp:
                codePath: zneus-telescope/Main.ipynb
                cpu_count: 14
                cpu_count_logical: 20
                disk:
                    /:
                        total: "1023187873792"
                        used: "413949267968"
                email: nikiokean20075@gmail.com
                executable: C:\Users\nikio\AppData\Local\Programs\Python\Python312\python.exe
                git:
                    commit: 6ebed1617943a6fc1301971a3fbb02d7454c5d78
                    remote: https://github.com/nikitaazz/zneus-telescope.git
                host: Nikita
                memory:
                    total: "16674258944"
                os: Windows-11-10.0.26200-SP0
                program: zneus-telescope/Main.ipynb
                python: CPython 3.12.3
                root: C:\Users\nikio\OneDrive\Рабочий стол\University\Zneus\project\zneus-telescope
                startedAt: "2025-11-06T16:12:24.626840Z"
                writerId: 9zod7pa6stccdx7oy2xhokz40f3afuzp
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
            "4": 3.12.3
            "5": 0.22.3
            "8":
                - 1
                - 3
            "12": 0.22.3
            "13": windows-amd64
